package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// skipNote records a backend that did not run and why. The reasons are as
// much a part of the report as the numbers: "sherpa has no GPU column" is a
// finding, and leaving it as an unexplained gap is how a reader concludes the
// benchmark simply forgot.
type skipNote struct {
	Backend string `json:"backend"`
	Reason  string `json:"reason"`
}

// report is the whole run: where it happened, what it measured, and what it
// could not. The JSON form is the artifact that survives — the Markdown is
// rendered from it, so a future run can be diffed against this one without
// re-parsing a table.
type report struct {
	Machine       machineInfo `json:"machine"`
	Audio         string      `json:"audio"`
	AudioSeconds  float64     `json:"audio_seconds"`
	Reference     string      `json:"reference_transcript"`
	RunsPerCell   int         `json:"runs_per_cell"`
	Threads       int         `json:"threads"`
	ModelDir      string      `json:"model_dir"`
	StreamChunkMS int         `json:"stream_chunk_ms"`

	WhisperCPUBackends []string `json:"whisper_cpu_backends,omitempty"`
	WhisperGPUBackends []string `json:"whisper_gpu_backends,omitempty"`

	Results      []runResult `json:"results"`
	NotInstalled []string    `json:"not_installed,omitempty"`
	Skipped      []skipNote  `json:"skipped,omitempty"`

	// The two sweeps vary a setting rather than a model, so they carry their
	// own cells rather than more rows in Results — a thread-scaling cell is
	// not comparable with a model row and must not be sorted alongside one.
	ThreadScaling []threadCell `json:"thread_scaling,omitempty"`
	WarmServer    []serverCell `json:"warm_server,omitempty"`
}

func writeJSON(path string, r *report) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	data, err := json.MarshalIndent(r, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, append(data, '\n'), 0o644)
}

// writeMarkdown renders the report. Every claim in it is traceable to a field
// in the JSON; where a number is absent the cell says why rather than being
// left blank, and the header states what the run could not measure before it
// states what it could.
func writeMarkdown(path string, r *report) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	var b strings.Builder

	// The frontmatter is assembled line by line rather than as one raw string
	// literal: the summary has to name `just bench` in backticks, and a Go raw
	// string cannot contain one.
	b.WriteString("---\n")
	b.WriteString("title: \"Measured Model Benchmarks\"\n")
	b.WriteString("author: \"Matthew Schulkind\"\n")
	fmt.Fprintf(&b, "date: %s\n", r.Machine.Timestamp.Format("2006-01-02"))
	b.WriteString("status: generated\n")
	b.WriteString("tags: [benchmarks, models, whisper, sherpa, gpu, vulkan, memory, accuracy]\n")
	b.WriteString("summary: \"Speed, peak memory, and accuracy for every installed model in mavor's catalog, on every backend this machine can actually run. Generated by `just bench`; every number came from a process that ran here.\"\n")
	b.WriteString("---\n\n")

	b.WriteString("# Measured Model Benchmarks\n\n")
	b.WriteString("> [!NOTE]\n")
	b.WriteString("> This file is generated by `just bench` ([`cmd/mavor-bench`](../../cmd/mavor-bench)).\n")
	b.WriteString("> Do not edit it by hand — rerun the harness. The raw results, including\n")
	b.WriteString("> full transcripts, are in [`benchmarks/latest.json`](benchmarks/latest.json).\n\n")

	writeRunContext(&b, r)
	writeSkips(&b, r)
	writeSpeedTable(&b, r)
	writeMemoryTable(&b, r)
	writeAccuracyTable(&b, r)
	writeStreamingSection(&b, r)
	writeThreadScalingSection(&b, r)
	writeWarmServerSection(&b, r)
	writeFailures(&b, r)
	writeMethod(&b, r)

	return os.WriteFile(path, []byte(b.String()), 0o644)
}

func writeRunContext(b *strings.Builder, r *report) {
	b.WriteString("## The machine these numbers came from\n\n")
	b.WriteString("A benchmark without its hardware is a number without units. Rerun the\n")
	b.WriteString("harness on another machine and compare against this block, not against\n")
	b.WriteString("the memory of what was fast here.\n\n")
	b.WriteString("| | |\n|---|---|\n")
	row := func(k, v string) {
		if strings.TrimSpace(v) != "" {
			fmt.Fprintf(b, "| **%s** | %s |\n", k, v)
		}
	}
	row("Run at", r.Machine.Timestamp.Format(time.RFC3339))
	row("Host", r.Machine.Hostname)
	row("OS / arch", r.Machine.OS+" / "+r.Machine.Arch)
	row("CPU", fmt.Sprintf("%s (%d logical cores)", orUnknown(r.Machine.CPUModel), r.Machine.CPUCores))
	if r.Machine.MemTotalKB > 0 {
		row("RAM", fmt.Sprintf("%.1f GB", float64(r.Machine.MemTotalKB)/1024/1024))
	}
	if r.Machine.GPUName != "" {
		row("GPU", fmt.Sprintf("%s (%s, Vulkan %s)", r.Machine.GPUName, r.Machine.GPUDriver, r.Machine.VulkanAPI))
	} else {
		row("GPU", "none enumerated")
	}
	row("Go", r.Machine.GoVersion)
	row("mavor commit", r.Machine.MavorCommit)
	row("Audio", fmt.Sprintf("`%s` (%.2f s)", r.Audio, r.AudioSeconds))
	row("Threads", fmt.Sprint(r.Threads))
	row("Runs per cell", fmt.Sprintf("%d (median reported)", r.RunsPerCell))
	// Contention is the one distortion the median of three runs does not
	// smooth away, so the report has to hand the reader the evidence rather
	// than leave a slow row looking like a slow model.
	if r.Machine.LoadBefore > 0 || r.Machine.LoadAfter > 0 {
		note := ""
		if busy := loadIsHigh(r.Machine, r.Threads); busy != "" {
			note = " — " + busy
		}
		row("Load average (1 min)", fmt.Sprintf("%.2f before, %.2f after%s",
			r.Machine.LoadBefore, r.Machine.LoadAfter, note))
	}
	if len(r.WhisperCPUBackends) > 0 {
		row("whisper CPU build loads", "`"+strings.Join(r.WhisperCPUBackends, "`, `")+"`")
	}
	if len(r.WhisperGPUBackends) > 0 {
		row("whisper GPU build loads", "`"+strings.Join(r.WhisperGPUBackends, "`, `")+"`")
	}
	b.WriteString("\n")
}

// loadIsHigh returns a warning when the machine was busy enough that the
// timings describe the contention as much as the models.
//
// The threshold is twice the thread count, and the reasoning is worth stating
// because the obvious threshold is wrong. A sweep running one worker at
// `threads` threads puts a load of roughly `threads` on the machine all by
// itself, and LoadAfter is read while that is still true — so anything keyed
// on the core count fires on every honest run and teaches the reader to skip
// the line. Doubling it leaves room for the sweep's own load plus ordinary
// background noise, and still catches what this exists to catch: the run that
// measured a model 2.5x slow at a load of 14 on a 6-thread sweep.
//
// Under a container these are the HOST's figures — /proc/loadavg is not
// namespaced — which is the number that matters, since the competing process
// does not have to be in here to take the CPU.
func loadIsHigh(m machineInfo, threads int) string {
	if threads <= 0 {
		return ""
	}
	threshold := float64(threads) * 2
	peak := m.LoadBefore
	if m.LoadAfter > peak {
		peak = m.LoadAfter
	}
	if peak <= threshold {
		return ""
	}
	return fmt.Sprintf("**the machine was busy** (peak %.2f, over the %.0f this sweep accounts for); treat these timings as a floor, not a measurement",
		peak, threshold)
}

func writeSkips(b *strings.Builder, r *report) {
	if len(r.Skipped) == 0 && len(r.NotInstalled) == 0 {
		return
	}
	b.WriteString("## What this run could not measure\n\n")
	b.WriteString("Stated first, so no reader mistakes an absent row for a slow one.\n\n")
	if len(r.Skipped) > 0 {
		b.WriteString("| Backend | Why it did not run |\n|---|---|\n")
		for _, s := range r.Skipped {
			fmt.Fprintf(b, "| `%s` | %s |\n", s.Backend, s.Reason)
		}
		b.WriteString("\n")
	}
	if len(r.NotInstalled) > 0 {
		fmt.Fprintf(b, "**Not downloaded, so not benchmarked** (%d): %s.\n\n",
			len(r.NotInstalled), "`"+strings.Join(r.NotInstalled, "`, `")+"`")
		b.WriteString("Get them with `mavor models pull <name>` and rerun; the harness picks up\n")
		b.WriteString("whatever is in the cache, so no list here needs updating.\n\n")
	}
}

func writeSpeedTable(b *strings.Builder, r *report) {
	rows := successful(r.Results)
	if len(rows) == 0 {
		return
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].RTF < rows[j].RTF })

	b.WriteString("## Speed\n\n")
	fmt.Fprintf(b, "Total wall time to transcribe %.2f s of speech, including model load.\n", r.AudioSeconds)
	b.WriteString("RTF is that time over the audio duration: **below 1.0 is faster than real\n")
	b.WriteString("time**, and the last column is the same thing read the friendly way.\n")
	b.WriteString("Sorted fastest first.\n\n")
	b.WriteString("| Model | Backend | Total | RTF | Speed |\n|---|---|---:|---:|---:|\n")
	for _, x := range rows {
		fmt.Fprintf(b, "| `%s` | %s | %s | %.3f | %.1f× real time |\n",
			x.Model, x.Backend.label(), msString(x.TotalMS), x.RTF, 1/x.RTF)
	}
	b.WriteString("\n")
}

func writeMemoryTable(b *strings.Builder, r *report) {
	rows := successful(r.Results)
	if len(rows) == 0 {
		return
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].PeakRSSKB < rows[j].PeakRSSKB })

	b.WriteString("## Memory\n\n")
	b.WriteString("Peak resident set size, from `getrusage(RUSAGE_CHILDREN)` — the true\n")
	b.WriteString("high-water mark of a process that loaded exactly one model. Both engines\n")
	b.WriteString("are measured the same way: `whisper-cli` is already a subprocess, and\n")
	b.WriteString("each sherpa model runs in a worker process for the same reason.\n\n")
	b.WriteString("> [!IMPORTANT]\n")
	b.WriteString("> None of these are VRAM. The GPU rows report host memory only — nothing\n")
	b.WriteString("> here measures what the card allocated.\n\n")
	b.WriteString("| Model | Backend | Peak RSS |\n|---|---|---:|\n")
	for _, x := range rows {
		fmt.Fprintf(b, "| `%s` | %s | %s |\n", x.Model, x.Backend.label(), memString(x.PeakRSSKB))
	}
	b.WriteString("\n")
}

func writeAccuracyTable(b *strings.Builder, r *report) {
	rows := successful(r.Results)
	if len(rows) == 0 {
		return
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].WER < rows[j].WER })

	b.WriteString("## Accuracy\n\n")
	b.WriteString("Scored against the ground truth beside the fixture. WER and CER are\n")
	b.WriteString("computed on lowercased, unpunctuated text, so they measure recognition\n")
	b.WriteString("rather than formatting; punctuation and capitalization are scored\n")
	b.WriteString("separately on the raw output, because for dictation they are most of\n")
	b.WriteString("what makes a transcript usable without editing.\n\n")
	b.WriteString("**WER above 1.0 means hallucination** — more wrong words than the\n")
	b.WriteString("reference contains. It is deliberately not capped.\n\n")
	b.WriteString("| Model | Backend | WER | CER | Punct/word | Capital. F1 |\n|---|---|---:|---:|---:|---:|\n")
	for _, x := range rows {
		fmt.Fprintf(b, "| `%s` | %s | %.1f%% | %.1f%% | %.2f | %.2f |\n",
			x.Model, x.Backend.label(), x.WER*100, x.CER*100, x.PunctDens, x.CapF1)
	}
	b.WriteString("\n")
}

// writeStreamingSection exists because "streaming vs batch" is a different
// question from "which model is fastest", and answering it in the speed table
// would bury it. A streaming model's total time is not its selling point;
// time to first token is.
func writeStreamingSection(b *strings.Builder, r *report) {
	var streaming []runResult
	attempted := 0
	for _, x := range r.Results {
		if x.Backend.Mode != "streaming" {
			continue
		}
		attempted++
		if !x.Failed {
			streaming = append(streaming, x)
		}
	}

	// A streaming section that simply vanishes when every streaming model
	// failed is the exact failure this report exists to avoid: the reader
	// concludes streaming was not part of the run, rather than that it could
	// not be measured. Say it outright.
	if len(streaming) == 0 {
		b.WriteString("## Streaming vs batch\n\n")
		if attempted == 0 {
			b.WriteString("**Not measured.** No model in this run is marked as streaming, so there\n")
			b.WriteString("was no incremental decode to time.\n\n")
			return
		}
		fmt.Fprintf(b, "**Not measured.** All %d streaming attempts failed to load — see\n", attempted)
		b.WriteString("[Cells that failed](#cells-that-failed). Every streaming-capable model in\n")
		b.WriteString("the catalog is a sherpa model, so when sherpa cannot load them there is\n")
		b.WriteString("no incremental decode to measure anywhere.\n\n")
		b.WriteString("> [!WARNING]\n")
		b.WriteString("> This is a finding, not a gap in the benchmark. `mavor` advertises\n")
		b.WriteString("> streaming models in `mavor models list`, and on this machine none of\n")
		b.WriteString("> them can be loaded at all.\n\n")
		return
	}

	b.WriteString("## Streaming vs batch\n\n")
	fmt.Fprintf(b, "The streaming rows feed the same audio in %d ms chunks — the daemon's own\n", r.StreamChunkMS)
	b.WriteString("preview tick — rather than handing over a finished file, so the per-call\n")
	b.WriteString("cost the user actually waits through is inside these numbers.\n")
	b.WriteString("**Time to first token** is what decides whether a model starts feeling\n")
	b.WriteString("live; total time cannot tell you that, and neither can it tell you\n")
	b.WriteString("whether the preview kept coming — see [Preview cadence](#preview-cadence)\n")
	b.WriteString("below for that half of the answer.\n\n")
	b.WriteString("Only models the catalog marks as streaming appear here. Whisper is absent\n")
	b.WriteString("by architecture, not by omission: it is encoder-decoder over 30-second\n")
	b.WriteString("windows and has no incremental decode to measure.\n\n")
	b.WriteString("First token is measured from the first chunk, with the model already\n")
	b.WriteString("loaded — a daemon holds it warm long before anyone speaks, so folding a\n")
	b.WriteString("model load into this number would describe a wait no user experiences.\n")
	b.WriteString("Load is in the JSON as `load_ms`, and in the totals.\n\n")
	b.WriteString("| Model | First token | Streaming total | Batch total | Difference |\n|---|---:|---:|---:|---:|\n")

	batch := map[string]runResult{}
	for _, x := range successful(r.Results) {
		if x.Backend.Engine == "sherpa" && x.Backend.Mode == "batch" {
			batch[x.Model] = x
		}
	}
	for _, s := range streaming {
		first := "—"
		if s.FirstTokenMS > 0 {
			first = msString(s.FirstTokenMS)
		}
		batchCell, diff := "—", "—"
		if bt, ok := batch[s.Model]; ok {
			batchCell = msString(bt.TotalMS)
			diff = fmt.Sprintf("%+.0f ms", s.TotalMS-bt.TotalMS)
		}
		fmt.Fprintf(b, "| `%s` | %s | %s | %s | %s |\n", s.Model, first, msString(s.TotalMS), batchCell, diff)
	}
	b.WriteString("\nA dash under **first token** means the recognizer returned no partial text\n")
	b.WriteString("before the stream closed — it accepted the chunks but decoded only at the\n")
	b.WriteString("end, which is worth knowing about a model the catalog calls streaming.\n\n")

	writeCadenceTable(b, r, streaming)
}

// lumpyMeanGapMS is where a preview stops reading as continuous and starts
// reading as text arriving a phrase at a time.
//
// It is a judgement, not a perceptual constant, and the honest provenance is
// this: the two companions that have been used as the default sit around
// 260-360 ms between repaints and nobody has complained about them, while the
// one measured at ~720 ms was reported as chunky within a day of shipping.
// The line is drawn between those two. It gates nothing — the harness still
// publishes every number — it only decides whether the report says out loud
// that a row is a preview a user will notice.
const lumpyMeanGapMS = 500

// writeCadenceTable answers the question time to first token cannot: once the
// preview has started, does it keep coming?
//
// This exists because nothing did. An accurate streaming model was made the
// default companion, scored well here on first token, and a user reported the
// preview "comes in chunks rather than continuously" the next day. The report
// had no column that could have said so, and a benchmark that scores a
// regression well is worse than one that is silent about it.
func writeCadenceTable(b *strings.Builder, r *report, streaming []runResult) {
	measured := false
	for _, s := range streaming {
		if s.Updates > 0 {
			measured = true
			break
		}
	}
	b.WriteString("### Preview cadence\n\n")
	if !measured {
		b.WriteString("**Not measured.** No streaming row produced a single mid-stream update,\n")
		b.WriteString("so there are no intervals to report. That is itself the worst possible\n")
		b.WriteString("cadence result: the overlay would show nothing at all until the\n")
		b.WriteString("utterance ended.\n\n")
		return
	}

	b.WriteString("Time to first token says when the preview *starts*. It says nothing about\n")
	b.WriteString("whether the text then flows or arrives in lumps — and that is the half a\n")
	b.WriteString("user notices. An **update** is a chunk whose returned text differs from\n")
	b.WriteString("the previous chunk's: one repaint of the overlay.\n\n")

	b.WriteString("| Model | Updates | Mean gap | Longest gap | Slowest chunk |\n")
	b.WriteString("|---|---:|---:|---:|---:|\n")
	tick := float64(r.StreamChunkMS)
	overrun := false
	for _, s := range streaming {
		if s.Updates == 0 {
			fmt.Fprintf(b, "| `%s` | 0 | — | — | %s |\n", s.Model, msString(s.SlowestChunkMS))
			continue
		}
		slow := msString(s.SlowestChunkMS)
		if tick > 0 && s.SlowestChunkMS > tick {
			// Bold rather than a symbol: the warning below names the models,
			// and a reader scanning the column still needs the cell itself to
			// stand out.
			slow = "**" + slow + "**"
			overrun = true
		}
		fmt.Fprintf(b, "| `%s` | %d | %s | %s | %s |\n",
			s.Model, s.Updates, msString(s.MeanGapMS), msString(s.MaxGapMS), slow)
	}
	b.WriteString("\n")

	b.WriteString("**Mean gap** and **longest gap** are distances in *audio time* — position\n")
	b.WriteString("in the stream — not wall clock. The harness feeds chunks as fast as the\n")
	b.WriteString("recognizer accepts them, so a wall-clock gap would report how fast this\n")
	b.WriteString("CPU is rather than how the model behaves, and would shrink on a faster\n")
	b.WriteString("machine while the lumpiness a user sees stayed exactly the same. The wait\n")
	b.WriteString("*before* the first update is excluded — that is first token, above — and\n")
	b.WriteString("the silence *after* the last one is included, so a model that emits a few\n")
	b.WriteString("partials early, goes quiet, and delivers the rest at the end of the\n")
	b.WriteString("stream cannot score a clean mean.\n\n")

	b.WriteString("**Slowest chunk** is the exception: it is wall clock, because it is the\n")
	fmt.Fprintf(b, "longest single `FeedChunk` call and the daemon has only %d ms before the\n", r.StreamChunkMS)
	b.WriteString("next chunk is due.\n\n")

	b.WriteString("How to read the update count: it is repaints across the whole fixture, so\n")
	fmt.Fprintf(b, "divide by the %.1f s of audio. Three or four repaints a second reads as\n", r.AudioSeconds)
	fmt.Fprintf(b, "continuous text appearing as you speak. A mean gap past about %d ms does\n", lumpyMeanGapMS)
	b.WriteString("not: the overlay sits still and then jumps a phrase at a time, which is\n")
	b.WriteString("what a user reports as \"it comes in chunks rather than continuously\".\n")
	b.WriteString("**Longest gap** is the worst of those freezes and is the number that\n")
	b.WriteString("predicts the complaint — a healthy mean with a 1.3 s worst case still\n")
	b.WriteString("feels to the speaker like the preview stopped.\n\n")

	writeLumpyPreviewWarning(b, r, streaming)
	writeTickOverrunWarning(b, r, streaming, overrun)
}

// writeLumpyPreviewWarning states the conclusion instead of leaving the reader
// to derive it. "26 updates" is not self-interpreting; "a repaint every
// 716 ms, which is a preview arriving in visible lumps" is, and a table nobody
// can read is how the last regression got shipped.
func writeLumpyPreviewWarning(b *strings.Builder, r *report, streaming []runResult) {
	var lumpy []runResult
	for _, s := range streaming {
		if s.Updates > 0 && s.MeanGapMS > lumpyMeanGapMS {
			lumpy = append(lumpy, s)
		}
	}
	if len(lumpy) == 0 {
		return
	}
	b.WriteString("> [!WARNING]\n")
	b.WriteString("> **These models paint the preview in lumps, whatever their first-token\n")
	b.WriteString("> figure says.** Do not pick one as `preview.source` on the strength of\n")
	b.WriteString("> the latency table alone.\n>\n")
	for _, s := range lumpy {
		fmt.Fprintf(b, "> - `%s` — %d updates over %.1f s of audio: a repaint\n", s.Model, s.Updates, r.AudioSeconds)
		fmt.Fprintf(b, ">   every %s on average, with a longest freeze of %s. The overlay holds\n",
			msString(s.MeanGapMS), msString(s.MaxGapMS))
		b.WriteString(">   still, then jumps a phrase at a time.\n")
	}
	b.WriteString("\n")
}

// writeTickOverrunWarning flags a model whose slowest FeedChunk exceeded the
// daemon's preview tick. That is not a slow row, it is a model the daemon
// cannot drive: the preview goroutine is still inside the recognizer when the
// next chunk is due, so captured audio queues up behind it and the overlay
// falls further behind the speaker the longer the utterance runs.
func writeTickOverrunWarning(b *strings.Builder, r *report, streaming []runResult, overrun bool) {
	if !overrun || r.StreamChunkMS <= 0 {
		return
	}
	b.WriteString("> [!CAUTION]\n")
	fmt.Fprintf(b, "> **A bold slowest-chunk figure overran the daemon's %d ms preview tick.**\n", r.StreamChunkMS)
	b.WriteString("> The daemon feeds the preview from a ticker on one goroutine, so a\n")
	b.WriteString("> `FeedChunk` that takes longer than the interval cannot be absorbed:\n")
	b.WriteString("> captured audio backs up behind the recognizer and the overlay drifts\n")
	b.WriteString("> further behind the speaker the longer the utterance runs. Unlike the gap\n")
	b.WriteString("> columns this one is wall clock, so it is a claim about this machine —\n")
	b.WriteString("> a slower CPU pushes more models over the line, and that is the point:\n")
	b.WriteString("> it is measured where the daemon would run. `stream_slow_chunks` in the\n")
	b.WriteString("> JSON says how many calls overran, which separates one hiccup from a\n")
	b.WriteString("> model that can never keep up.\n>\n")
	for _, s := range streaming {
		if s.SlowestChunkMS > float64(r.StreamChunkMS) {
			detail := ""
			if s.SlowChunks > 0 {
				calls := "calls"
				if s.SlowChunks == 1 {
					calls = "call"
				}
				detail = fmt.Sprintf(", %d %s over the tick", s.SlowChunks, calls)
			}
			fmt.Fprintf(b, "> - `%s` — worst call %s%s.\n", s.Model, msString(s.SlowestChunkMS), detail)
		}
	}
	b.WriteString("\n")
}

// writeThreadScalingSection answers the `threads` config key. It is a
// separate table because it varies a setting on a fixed model, which is the
// opposite of every table above it, and mixing the two would invite a reader
// to compare a 2-thread cell against a GPU row.
func writeThreadScalingSection(b *strings.Builder, r *report) {
	b.WriteString("## Thread scaling\n\n")
	if len(r.ThreadScaling) == 0 {
		b.WriteString("**Not measured** in this run — see [What this run could not\n")
		b.WriteString("measure](#what-this-run-could-not-measure).\n\n")
		return
	}
	b.WriteString("How much `threads` in `config.toml` is worth, on the stock CPU build.\n")
	b.WriteString("Each row is the same audio and the same median-of-N as the tables above,\n")
	b.WriteString("with only `-t` changed. Speedup is against the same model's slowest\n")
	b.WriteString("thread count here, so it reads as what the extra cores bought.\n\n")

	slowest := map[string]float64{}
	for _, c := range r.ThreadScaling {
		if !c.Failed && c.TotalMS > slowest[c.Model] {
			slowest[c.Model] = c.TotalMS
		}
	}

	b.WriteString("| Model | Threads | Total | RTF | Speedup vs slowest | Peak RSS |\n")
	b.WriteString("|---|---:|---:|---:|---:|---:|\n")
	for _, c := range r.ThreadScaling {
		if c.Failed {
			fmt.Fprintf(b, "| `%s` | %d | failed | — | — | — |\n", c.Model, c.Threads)
			continue
		}
		speedup := "—"
		if base := slowest[c.Model]; base > 0 && c.TotalMS > 0 {
			speedup = fmt.Sprintf("%.2f×", base/c.TotalMS)
		}
		fmt.Fprintf(b, "| `%s` | %d | %s | %.3f | %s | %s |\n",
			c.Model, c.Threads, msString(c.TotalMS), c.RTF, speedup, memString(c.PeakRSSKB))
	}
	b.WriteString("\nThread counts above the machine's physical cores are included on purpose:\n")
	b.WriteString("where the curve flattens or turns back is the useful part of the answer,\n")
	b.WriteString("and it cannot be read off a curve that stops at the optimum.\n\n")
}

// writeWarmServerSection answers the default placement for a whisper model:
// whether keeping the model in memory between utterances is worth running a
// child process for. It is what `advanced.placement = "subprocess"` opts out
// of.
func writeWarmServerSection(b *strings.Builder, r *report) {
	b.WriteString("## Warm server vs cold CLI\n\n")
	if len(r.WarmServer) == 0 {
		b.WriteString("**Not measured** in this run — see [What this run could not\n")
		b.WriteString("measure](#what-this-run-could-not-measure).\n\n")
		return
	}
	b.WriteString("`advanced.placement = \"subprocess\"` spawns `whisper-cli` per utterance and\n")
	b.WriteString("reloads the model every time; the default placement for a whisper model\n")
	b.WriteString("keeps a `whisper-server` child warm and posts the audio to it. The warm\n")
	b.WriteString("column is the per-utterance time with the\n")
	b.WriteString("model already resident. Startup is what the daemon pays once, at login,\n")
	b.WriteString("and is excluded from it.\n\n")
	b.WriteString("These rows drive `internal/speech`, the same client the daemon uses, so\n")
	b.WriteString("what is measured is the code path a user gets rather than a stand-in.\n\n")
	b.WriteString("| Model | Threads | Warm | Cold CLI | Saved | Startup | RTF |\n")
	b.WriteString("|---|---:|---:|---:|---:|---:|---:|\n")
	for _, c := range r.WarmServer {
		if c.Failed {
			fmt.Fprintf(b, "| `%s` | %d | failed | — | — | — | — |\n", c.Model, c.Threads)
			continue
		}
		cold, saved := "—", "—"
		if c.ColdMS > 0 {
			cold = msString(c.ColdMS)
			saved = fmt.Sprintf("%+.0f ms", c.WarmMS-c.ColdMS)
		}
		fmt.Fprintf(b, "| `%s` | %d | %s | %s | %s | %s | %.3f |\n",
			c.Model, c.Threads, msString(c.WarmMS), cold, saved, msString(c.StartupMS), c.RTF)
	}
	b.WriteString("\nA negative **saved** figure is the server winning. Peak memory is absent\n")
	b.WriteString("from this table on purpose: the server is a long-lived child of the\n")
	b.WriteString("harness rather than a process that exits per run, so the `getrusage`\n")
	b.WriteString("high-water mark the memory table uses does not apply to it.\n\n")
}

func writeFailures(b *strings.Builder, r *report) {
	var failed []runResult
	for _, x := range r.Results {
		if x.Failed {
			failed = append(failed, x)
		}
	}
	if len(failed) == 0 {
		return
	}
	b.WriteString("## Cells that failed\n\n")
	b.WriteString("These ran and did not produce a transcript. They are listed rather than\n")
	b.WriteString("dropped, because a model that cannot run is a result.\n\n")
	b.WriteString("| Model | Backend | Error |\n|---|---|---|\n")
	for _, x := range failed {
		fmt.Fprintf(b, "| `%s` | %s | %s |\n", x.Model, x.Backend.label(), oneLine(x.Error))
	}
	b.WriteString("\n")
}

func writeMethod(b *strings.Builder, r *report) {
	b.WriteString("## How to rerun this\n\n")
	b.WriteString("```console\n")
	b.WriteString("$ just bench            # every backend: whisper on CPU, the in-process\n")
	b.WriteString("                        # sherpa engines, and GPU if a Vulkan build is present\n")
	b.WriteString("$ just bench-gpu-build  # build the Vulkan whisper.cpp the GPU column needs\n")
	b.WriteString("```\n\n")
	b.WriteString("Method, so a rerun elsewhere means the same thing:\n\n")
	fmt.Fprintf(b, "- Each cell runs **%d times** and the report takes the **median**, not the\n", r.RunsPerCell)
	b.WriteString("  mean (one scheduler stall would move a mean of three) and not the best\n")
	b.WriteString("  case (nobody experiences the best case).\n")
	b.WriteString("- Timings are **cold-start totals**: model load plus inference, which is\n")
	b.WriteString("  what a user waits through. The `sherpa` rows break load out separately\n")
	b.WriteString("  in the JSON, because a daemon that keeps a model warm pays it once.\n")
	fmt.Fprintf(b, "- The filesystem cache is **warm** by the second run of each cell, and %d of\n", r.RunsPerCell)
	b.WriteString("  the runs see it warm. Treat the numbers as steady-state, not first-boot.\n")
	b.WriteString("- The GPU column comes from an out-of-tree whisper.cpp built with\n")
	b.WriteString("  `-DGGML_VULKAN=ON`. The CPU and GPU rows use **the same binary**,\n")
	b.WriteString("  differing only in whisper.cpp's `-ng` flag, so the comparison isolates\n")
	b.WriteString("  the backend rather than the build.\n")
	b.WriteString("- Each sherpa model runs in its own **worker process**. sherpa-onnx\n")
	b.WriteString("  reports a model it cannot load by aborting from C++ rather than\n")
	b.WriteString("  returning an error, so without isolation one bad model would end the\n")
	b.WriteString("  sweep and lose every result before it.\n")
	b.WriteString("- Before publishing a GPU column the harness checks that the build\n")
	b.WriteString("  actually loaded a GPU backend and that a Vulkan device enumerated. If\n")
	b.WriteString("  either check fails it refuses the column and says so above, rather than\n")
	b.WriteString("  reporting CPU numbers under a GPU heading.\n\n")
}

func successful(all []runResult) []runResult {
	var out []runResult
	for _, x := range all {
		if !x.Failed {
			out = append(out, x)
		}
	}
	return out
}

func msString(ms float64) string {
	if ms >= 1000 {
		return fmt.Sprintf("%.2f s", ms/1000)
	}
	return fmt.Sprintf("%.0f ms", ms)
}

func memString(kb int64) string {
	if kb <= 0 {
		return "—"
	}
	if kb >= kbPerMB*kbPerMB {
		return fmt.Sprintf("%.2f GB", float64(kb)/kbPerMB/kbPerMB)
	}
	return fmt.Sprintf("%.0f MB", float64(kb)/kbPerMB)
}

func orUnknown(s string) string {
	if strings.TrimSpace(s) == "" {
		return "unknown"
	}
	return s
}

func oneLine(s string) string {
	return strings.Join(strings.Fields(strings.ReplaceAll(s, "|", "\\|")), " ")
}
